[package]
name = "construct-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "construct"
path = "src/main.rs"

[dependencies]
construct-core = { path = "../construct-core" }
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
