ignore-build-dependencies = true
ignore-dev-dependencies = true

accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "MPL-2.0",
    "0BSD",
    "CDLA-Permissive-2.0",
]

[bedrock_level.clarify]
license = "Apache-2.0"
[[bedrock_level.clarify.files]]
path = "../../LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[bedrock_shared.clarify]
license = "Apache-2.0"
[[bedrock_shared.clarify.files]]
path = "../../LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[bedrock_macros.clarify]
license = "Apache-2.0"
[[bedrock_macros.clarify.files]]
path = "../../LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[bedrock_protocol_core.clarify]
license = "Apache-2.0"
[[bedrock_protocol_core.clarify.files]]
path = "../../LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[leveldb-sys.clarify]
license = "Apache-2.0 AND BSD-3-Clause AND Zlib"
[[leveldb-sys.clarify.files]]
path = "LICENSE"
license = "Apache-2.0"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"
[[leveldb-sys.clarify.files]]
path = "ffi/leveldb/LICENSE"
license = "BSD-3-Clause"
checksum = "ccc19f1da0798ed666609b65a5b44dd8b3abe6fc08b9c0592eb76e82e174db19"
[[leveldb-sys.clarify.files]]
path = "ffi/leveldb/lib/zlib/README"
license = "Zlib"
start = "Copyright notice:"
end = "  jloup@gzip.org          madler@alumni.caltech.edu"
checksum = "e6627a48eb017ea808ca78360582a0a84b564d5a13070af0640b026bb43adadc"
